### ISSUE TITLE
Updater: Add ability to configure and use specific major version of Composer

### ISSUE THREAD

**Issue by CoderBrandon** [waffle-ops/waffle#82]
Different projects may need to use v1 instead of v2 or some projects may be upgraded to v2 but we want to keep v1 installed locally.

Possible solution:
run `composer self-update --1` or `composer self-update --2` during update tasks and then reverse (if needed) at the end of task.

**Comment by daceej** [comment]
I think our best bet for this is to implement a `composer_bin` item in config -- at least for now. This was sort of on the horizon anyway with Lando support so that something like `composer_bin: 'lando composer'` could be used.

If users had composer 1.x and composer 2.x both installed, this could be done with `composer_bin: composer2` in a `.waffle.local.yml` file so that globally they use composer 1.x but that specific project would be 2.x. If we allow this config item in the global scope (I think we should) a user could tell Waffle to use a specific version of composer unless overridden by a project or local config file.

Thoughts? It does create some extra effort on the dev using the tool, but I think we are within our rights to require that. Ideally this problem will go away as composer 1.x fades away. The benefit is that we already know we need something to solve for this type of use case and this can take advantage of it (with minimal effort -- users just need install and tell Waffle which they prefer to use);

**Comment by CoderBrandon** [comment]
I think that could work. Having the updater call `--self-update` to alter the dev's tooling stack def isn't ideal.

**Comment by daceej** [comment]
Existing code for this was pushed with v0.0.5-alpha.
